version: '3.7'

services:

  spacex:
    container_name: spacex_launch
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8081:8080
    environment:
      - CHOKIDAR_USEPOLLING=true